title: Analoge elektronische schakelingen
author: Jan Genoe (jan.genoe@kuleuven.be)
logo: images/logo.png
description: Aanvulling bij de cursus Analoge Elektronica aan de KULeuven
only_build_toc_files: true
repository:
  url: https://github.com/jangenoe/InteractieveCursus
  path_to_book: AnalogeElektronica2 
html:
  favicon: images/favicon.ico
  use_issues_button: true
  use_edit_page_button: true
  use_repository_button: true
  # extra_navbar    : <a href="https://www.kuleuven.be"> <img src=" https://stijl.kuleuven.be/2016tmp/img/svg/logo.svg" alt="KULeuven"></a> 
execute:
  execute_notebooks: "off"
launch_buttons:
  notebook_interface: "jupyterlab"
  binderhub_url: "https://mybinder.org"
  colab_url: "https://colab.research.google.com"
  use_lite_button: false
  use_reveal_button: true
  use_powerpoint_button: false
  use_deck_button: false
parse:
  myst_enable_extensions:
    - amsmath
    - colon_fence
    # - deflist
    - dollarmath
    # - html_admonition
    # - html_image
    - linkify
    # - replacements
    # - smartquotes
    - substitution
    - tasklist
latex:
  latex_documents:
     targetname: python.tex
bibtex_bibfiles: 
  - AnalogeElektronica2.bib
sphinx:
  extra_extensions:
    - sphinx_exercise
    - sphinxext.opengraph
  config:
    # html_theme: sphinx_book_theme  # is reeds default
    language: nl
    html_show_copyright: false
    nb_remove_code_source: true
    # Pygments styling configuration
    pygments_style: 'default'
    highlight_language: 'python'
    # Custom code highlighting
    html_theme_options:
      pygment_light_style: 'default'
      pygment_dark_style: 'native'
    numfig_format : 
       figure: 'Figuur %s'
       code-block: 'Spice Listing %s'
       exercise: "Opdracht %s"
       table: 'Tabel %s'
    numfig_secnum_depth : 1
    # Enable separate numbering for different content types
    numfig : true
    # Custom figure classes will use different counters
    html_theme_options:
      extra_navbar: ""
    # templates_path : ["_templates"]
    # html_sidebars : {"**": ["navbar-logo.html","search-field.html","sbt-sidebar-nav.html","kuleuven.html"]}                     #.html mag weg
    # navbar_end: ["deck-lite-button.html"]
    html_static_path : ['_static']
    html_css_files : ['custom.css', 'code-caption-style.css', 'custom-pygments.css']   
    latex_logo: images/logo.png
    latex_elements:
      extraclassoptions: 'openany,oneside'
      papersize: 'a4paper'
    bibtex_reference_style: label
    bibtex_default_style : "unsrt"
    
    ogp_site_url: "https://jangenoe.github.io/jangenoe/InteractieveCursus/AnalogeElektronica2/intro.html"
    ogp_image: "https://jangenoe.github.io/InteractieveCursus/AnalogeElektronica2/_static/logo.svg"
    ogp_description_length: 200
