title: Analoge elektronische schakelingen
author: Jan Genoe (jan.genoe@kuleuven.be)
copyright: "2022" 
logo: images/logo.svg
only_build_toc_files: true
repository:
  url: https://github.com/jangenoe/InteractieveCursus
  path_to_book: AnalogeElektronica2 
html:
  use_issues_button: true
  use_edit_page_button: true
  use_repository_button: true
  extra_navbar    : <a href="https://www.kuleuven.be"> <img src=" http://stijl.kuleuven.be/2016tmp/img/svg/logo.svg" alt="KULeuven"></a>
execute:
  execute_notebooks: "off"
launch_buttons:
  notebook_interface: "jupyterlab"
  binderhub_url: "https://mybinder.org"
  colab_url: "https://colab.research.google.com"
parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - amsmath
    - colon_fence
    # - deflist
    - dollarmath
    # - html_admonition
    # - html_image
    - linkify
    # - replacements
    # - smartquotes
    - substitution
    - tasklist
sphinx:
  config:
    language: nl
    togglebutton_hint: " "
    html_show_copyright: false
    nb_render_figure_options: {"caption":"caption to be completed"}