name: cursus-environment
channels:
  - conda-forge
dependencies:
  - python>=3
  - pandoc
  - ipykernel
  - pip
  - sphinx-material
  - jupyterlab
  - matplotlib
  - pandas
  - numpy
  - scipy
  - scikit-rf
  - pip:
    - nbsphinx