title: Analog Design Techniques
author: Jan Genoe (jan.genoe@kuleuven.be)
logo: images/logo.svg
description: additional info for the lectures of Analog Design Techniques at the KULeuven
only_build_toc_files: true
repository:
  url: https://github.com/jangenoe/InteractieveCursus
  path_to_book: AnalogDesignTechniques
  branch: master 
html:
  favicon: images/favicon.ico
  use_issues_button: true
  use_edit_page_button: true
  use_repository_button: true
  extra_navbar    : <a href="https://www.kuleuven.be"><img src=" https://stijl.kuleuven.be/2016tmp/img/svg/logo.svg" alt="KULeuven"></a> 
execute:
  execute_notebooks: "off"
launch_buttons:
  notebook_interface: "jupyterlab"
  binderhub_url: "https://mybinder.org"
  colab_url: "https://colab.research.google.com"
  use_lite_button: false
  use_reveal_button: true
  use_powerpoint_button: false
  use_deck_button: false
parse:
  myst_enable_extensions:
    - amsmath
    - colon_fence
    # - deflist
    - dollarmath
    # - html_admonition
    # - html_image
    - linkify
    # - replacements
    # - smartquotes
    - substitution
    - tasklist
bibtex_bibfiles:
  - AnalogDesignTechniques.bib
sphinx:
  extra_extensions:
    - sphinx_exercise
    - sphinxext.opengraph
  config:
    html_theme: sphinx_book_theme
    language: en
    nb_remove_code_source: true
    html_show_copyright: false
    numfig_format : 
       code-block: 'Spice Listing %s'
    bibtex_reference_style: label
    bibtex_default_style : "unsrt"
    
    ogp_site_url: "https://jangenoe.github.io/jangenoe/InteractieveCursus/AnalogDesignTechniques/intro.html"
    ogp_image: "https://jangenoe.github.io/InteractieveCursus/AnalogDesignTechniques/_static/logo.svg"
    ogp_description_length: 200
