title: Toegepaste Analoge Elektronica
author: Jan Genoe (jan.genoe@kuleuven.be)
logo: images/logo.svg
description: Aanvulling bij de cursus ToegepasteAnalogeElektronica aan de KULeuven
only_build_toc_files: true
repository:
  url: https://github.com/jangenoe/InteractieveCursus
  path_to_book: ToegepasteAnalogeElektronica 
html:
  favicon: images/favicon.ico
  use_issues_button: true
  use_edit_page_button: true
  use_repository_button: true
  extra_navbar    : <a href="https://www.kuleuven.be"> <img src=" http://stijl.kuleuven.be/2016tmp/img/svg/logo.svg" alt="KULeuven"></a>
execute:
  execute_notebooks: "off"
launch_buttons:
  notebook_interface: "jupyterlab"
  binderhub_url: "https://mybinder.org"
  colab_url: "https://colab.research.google.com"
parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - amsmath
    - colon_fence
    # - deflist
    - dollarmath
    # - html_admonition
    # - html_image
    - linkify
    # - replacements
    # - smartquotes
    - substitution
    - tasklist
sphinx:
  extra_extensions:
    - sphinx_exercise
 #   - sphinxcontrib.spicelabel
  config:
    language: nl
    html_show_copyright: false
    nb_remove_code_source: true
    numfig_format : 
       code-block: 'Spice Listing %s'
       exercise: "Opdracht %s"

