title: Toegepaste Analoge Elektronica
author: Jan Genoe (jan.genoe@kuleuven.be)
logo: images/logo.png
description: Aanvulling bij de cursus ToegepasteAnalogeElektronica aan de KULeuven
only_build_toc_files: true
repository:
  url: https://github.com/jangenoe/InteractieveCursus
  path_to_book: ToegepasteAnalogeElektronica 
html:
  favicon: images/favicon.ico
  use_issues_button: true
  use_edit_page_button: true
  use_repository_button: true
  extra_navbar    : <a href="https://www.kuleuven.be"> <img src=" https://stijl.kuleuven.be/2016tmp/img/svg/logo.svg" alt="KULeuven"></a> 
  home_page_in_navbar: true
execute:
  execute_notebooks: "off"
launch_buttons:
  notebook_interface: "jupyterlab"
  binderhub_url: "https://mybinder.org"
  colab_url: "https://colab.research.google.com"
  #deepnote_url": "https://deepnote.com"
  #lightning_studio_url: "https://lightning.ai/"
  use_lite_button: false
  use_reveal_button: true
  use_powerpoint_button: false
  use_deck_button: false
parse:
  myst_enable_extensions:
    - amsmath
    - colon_fence
    # - deflist
    - dollarmath
    # - html_admonition
    # - html_image
    - linkify
    # - replacements
    # - smartquotes
    - substitution
    - tasklist
latex:
  latex_documents:
     targetname: python.tex
bibtex_bibfiles:
  - ToegepasteAnalogeElektronica.bib
sphinx:
  extra_extensions:
    - sphinx_exercise
    - sphinxext.opengraph
  config:
    html_extra_path: ['../ToegepasteAnalogeElektronica/video']
    # html_theme: sphinx_book_theme
    language: nl
    html_show_copyright: false
    nb_remove_code_source: true
    numfig_format : 
       code-block: 'Spice Listing %s'
       exercise: "Opdracht %s"
       
    latex_logo: images/logo.png
    latex_elements:
      extraclassoptions: 'openany,oneside'
      papersize: 'a4paper'
    bibtex_reference_style: label
    bibtex_default_style : "unsrt"
    
    ogp_site_url: "https://jangenoe.github.io/jangenoe/InteractieveCursus/ToegepasteAnalogeElektronica/intro.html"
    ogp_image: "https://jangenoe.github.io/InteractieveCursus/ToegepasteAnalogeElektronica/_static/logo.svg"
    ogp_description_length: 200
