channels:
  - conda-forge
dependencies:
  - jupyterhub==4.0.1
  - jupyterlab==4.0.4
  - nbgitpuller==1.2.0
  - jupyterlab-myst==2.0.1  # https://github.com/executablebooks/jupyterlab-myst PS:  for Jlab4.0 >=2.0.0
  - scikit-rf==0.28.0       # https://github.com/scikit-rf/scikit-rf
  - pyspice==1.5            # https://github.com/PySpice-org/PySpice
  - pip:
    - schemdraw==0.17       # https://github.com/cdelker/schemdraw
    - jupytercards==2.5.6   # https://github.com/jmshea/jupytercards (__version__ in __init__.py file maar niet in release, zie ook  https://pypi.org/project/jupytercards/#history )
    - wikitables==0.5.5     # https://github.com/bcicen/wikitables
variables:
  USEWIDGETS: True