# Een mybinder.org-ready environment om de jupyter notebooks in dit github repository te demonstreren.
# Deze environment is ook ideaal om ook thuis lokaal op Linux/MacOS/Windows deze jupyter notebooks uit te proberen.
# Dit zou dan ook exact dezelfde simulatieresultaten moeten geven als online beschikbaar en gebruikt in de cursus.
#
#   conda env update --file ./binder/environment.yml
#   conda activate KULeuven
#
name: KULeuven
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python
  - numpy
  - scipy
  - matplotlib-base
  - pip
  - sympy
  - jupyterlab
  - scikit-rf
  - networkx
  - ipywidgets
  - pyspice
  - pip:
    - schemdraw
    - jupytercards
    - wikitables
