# Een mybinder.org-ready environment om de jupyter notebooks in dit github repository te demonstreren.
# Deze environment is ook ideaal om ook thuis lokaal op Linux/MacOS/Windows deze jupyter noteboooks uit te proberen.
# Dit zou dan ook exact dezelfde simulatieresultaten moeten geven als online beschikbaar en gebruikt in de cursus.
#
#   conda env update --file ./binder/environment.yml
#   conda activate KULeuven
#
name: KULeuven
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.8
  - numpy
  - scipy
  - matplotlib-base
  - pip
  - sympy
  - jupyterlab
  - scikit-rf
  - networkx
  - ipywidgets
  - pip:
    - pyspice
    - schemdraw
    - jupytercards
