name: deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy-book:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install -r .github/requirements-Book.txt
        sudo apt-get install texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra latexmk
    - name: Build the Jupyterbook website
      run: |
        jb build CursusIndex/
        jb build ToegepasteAnalogeElektronica/
        jupyter nbconvert ToegepasteAnalogeElektronica/*.ipynb --to KULeuven  --no-prompt --no-input --output-dir=ToegepasteAnalogeElektronica/_build/html/slides
        sed -i -- 's:<img src="./images:<img src="../_images:g' ToegepasteAnalogeElektronica/_build/html/slides/*
        mv ToegepasteAnalogeElektronica/_build/html/ CursusIndex/_build/html/ToegepasteAnalogeElektronica
        jb build AnalogeElektronica2/
        jupyter nbconvert AnalogeElektronica2/*.ipynb --to KULeuven  --no-prompt --no-input --output-dir=AnalogeElektronica2/_build/html/slides
        sed -i -- 's:<img src="./images:<img src="../_images:g' AnalogeElektronica2/_build/html/slides/*
        mv AnalogeElektronica2/_build/html/ CursusIndex/_build/html/AnalogeElektronica2/
        jb build AnalogDesignTechniques/ 
        jupyter nbconvert AnalogDesignTechniques/*.ipynb --to KULeuven  --no-prompt --no-input --output-dir=AnalogDesignTechniques/_build/html/slides
        sed -i -- 's:<img src="./images:<img src="../_images:g' AnalogDesignTechniques/_build/html/slides/*
        mv AnalogDesignTechniques/_build/html/ CursusIndex/_build/html/AnalogDesignTechniques
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: CursusIndex/_build/html
        
  build-jupyter-lite:
    needs: build-and-deploy-book
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install the dependencies
      run: |
        pip install -r .github/requirements-Lite.txt
    - name: Copy common files
      run: |
        cp common/cursusdef_ToegepasteAnalogeElektronica_Lite.py ToegepasteAnalogeElektronica/cursusdef.py
        cp common/cursusdef_ToegepasteAnalogeElektronica_Lite.py AnalogeElektronica2/cursusdef.py
        cp common/cursusdef_ToegepasteAnalogeElektronica_Lite.py AnalogDesignTechniques/cursusdef.py
    - name: Build the JupyterLite site
      run: |
        jupyter lite build --lite-dir Lite --contents ToegepasteAnalogeElektronica --output-dir dist/ToegepasteAnalogeElektronica/
        jupyter lite build --lite-dir Lite --contents AnalogeElektronica2 --output-dir dist/AnalogeElektronica2/
        jupyter lite build --lite-dir Lite --contents AnalogDesignTechniques --output-dir dist/AnalogDesignTechniques/
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        destination_dir: Lite
    - name: Build the JupyterLite deck site
      run: |
        jupyter lite build --lite-dir LiteDeck --contents ToegepasteAnalogeElektronica --output-dir distdeck/ToegepasteAnalogeElektronica/
        jupyter lite build --lite-dir LiteDeck --contents AnalogeElektronica2 --output-dir distdeck/AnalogeElektronica2/
        jupyter lite build --lite-dir LiteDeck --contents AnalogDesignTechniques --output-dir distdeck/AnalogDesignTechniques/
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./distdeck
        destination_dir: Deck