name: Repo2Docker

on:
  push:
    branches:
      - master
    # Github tags (1.2.3) get corresponding dockerhub tag (DOCKER_IMAGE:1.2.3)
    tags:
      - '*'
    paths:
      - binder/*
      - .github/workflows/*
      - .github/requirements-Lite.txt
      - .github/requirements-Repo2Docker.txt
  pull_request:
    branches:
      - master
    paths:
      - binder/*
      - .github/workflows/*
      - .github/requirements-Lite.txt
      - .github/requirements-Repo2Docker.txt


env:
  CONTAINER_NAME: ${{ github.repository }} # user/repo format
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v1
    - name: Set Up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Enable Pip Cache
      # https://github.com/actions/cache/blob/master/examples.md#python---pip
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Dependencies
      run: |
        python --version
        pip install -r requirements.txt
    - name: Build Image
      # Add folder of artifacts related to build that anyone can download
      run: |
        if docker pull $CONTAINER_NAME:latest; then
          jupyter-repo2docker --cache-from $CONTAINER_NAME:latest --debug --user-name jovyan --user-id 1000 --no-run --image-name $CONTAINER_NAME:latest $PWD
        else
          jupyter-repo2docker --debug --user-name jovyan --user-id 1000 --no-run --image-name $CONTAINER_NAME:latest $PWD
        fi
        mkdir conda-packages
        docker run $CONTAINER_NAME:latest conda list > conda-packages/packages.txt
    - name: Archive Conda Package List
      # Seems that artifacts uploaded with restricted permissions, requiring chmod -R u+x to read content
      uses: actions/upload-artifact@v1
      with:
        name: conda-packages
        path: conda-packages
