name: dutch-spelling-check

# First we define the Action trigger
on:
  # In this case, we define a manual trigger (workflow_dispatch)
  workflow_dispatch

# Define one or more jobs to run via the action
jobs:

  # Set a job name
  dutch-spelling-demo:

    # Define the base os that will run the action
    runs-on: ubuntu-latest

    # The job will include one or more steps
    steps:

    # We need to get some files to work on...
    # Start by checking out the repository
    - uses: actions/checkout@v4

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    # The spelling checker requires some particular packages
    - name: Install Dutch spelling packages
    # Run a set of shell commands to install required packages
      run: |
        sudo apt-get update && sudo apt-get install -y aspell aspell-nl

        # Install the latest official pyspelling version (avoids 'imp' module error)
        python3 -m pip install --upgrade pip
        python3 -m pip install pyspelling

    # Spell check the files in ToegepasteAnalogeElektronica directory
    - name: spellcheck Dutch files
      # Note that we can force the use of a particular shell if required
      run: |
        # Create build directory for dictionaries
        mkdir -p build/dictionary
        touch typos.txt
        # The spellchecker typically displays to stdout
        # which is visible in the action run history view
        # The dutch-ipyspell.yml file defines the target file paths that the
        # spellchecker is applied to for Dutch spell checking
        # We can also force spellchecker output into a file
        pyspelling -c .github/dutch-ipyspell.yml | tee -a typos.txt || continue
        # Display the file contents
        cat typos.txt
      shell: bash
      # We could let the action fail on errors
      # If we want that halting behaviour, comment out the following line
      continue-on-error: true

    # Saving the spellchecker output to a file then displaying it,
    # rather than just displaying it,  may seem redundant
    # But we can upload the generated file to the Action report page
    # and make it available for download...
    - name: Upload all typos
      uses: actions/upload-artifact@v4
      with:
        name: typos
        path: |
         typos.txt