name: Link Checker

# First we define the Action trigger
on:
  # In this case, we define a manual trigger (workflow_dispatch)
  workflow_dispatch
  
jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Link Checker
        uses: mr8lu/link-validator@v1.0.1
        with:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}  # Optional
          directory: '.'  # Adjust the directory as needed

      - name: Check External Links
        continue-on-error: true
        timeout-minutes: 5
        if: always()
        run: |
          jb build book --builder linkcheck